packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  sharp: true
  unrs-resolver: true
