"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimForgeEventType = void 0;
var SimForgeEventType;
(function (SimForgeEventType) {
    SimForgeEventType["SCENARIO_CREATED"] = "scenario.created";
    SimForgeEventType["SCENARIO_PUBLISHED"] = "scenario.published";
    SimForgeEventType["SCENARIO_ARCHIVED"] = "scenario.archived";
    SimForgeEventType["RUN_SUBMITTED"] = "run.submitted";
    SimForgeEventType["RUN_APPROVED"] = "run.approved";
    SimForgeEventType["RUN_DISPATCHED"] = "run.dispatched";
    SimForgeEventType["RUN_COMPLETED"] = "run.completed";
    SimForgeEventType["RUN_FAILED"] = "run.failed";
    SimForgeEventType["RUN_CANCELLED"] = "run.cancelled";
    SimForgeEventType["SHARD_ASSIGNED"] = "shard.assigned";
    SimForgeEventType["SHARD_STARTED"] = "shard.started";
    SimForgeEventType["SHARD_COMPLETED"] = "shard.completed";
    SimForgeEventType["SHARD_FAILED"] = "shard.failed";
    SimForgeEventType["SHARD_CHECKPOINTED"] = "shard.checkpointed";
    SimForgeEventType["AGENT_SPAWNED"] = "agent.spawned";
    SimForgeEventType["AGENT_STATE_CHANGED"] = "agent.state_changed";
    SimForgeEventType["AGENT_COMPLETED"] = "agent.completed";
    SimForgeEventType["AGENT_FAILED"] = "agent.failed";
    SimForgeEventType["AGENT_LOOP_DETECTED"] = "agent.loop_detected";
    SimForgeEventType["ACTION_EXECUTED"] = "action.executed";
    SimForgeEventType["ACTION_SUCCEEDED"] = "action.succeeded";
    SimForgeEventType["ACTION_FAILED"] = "action.failed";
    SimForgeEventType["ACTION_RETRIED"] = "action.retried";
    SimForgeEventType["ACTION_DLQ_SENT"] = "action.dlq_sent";
    SimForgeEventType["REQUEST_SENT"] = "request.sent";
    SimForgeEventType["RESPONSE_RECEIVED"] = "response.received";
    SimForgeEventType["RESPONSE_TIMEOUT"] = "response.timeout";
    SimForgeEventType["FAILURE_DETECTED"] = "failure.detected";
    SimForgeEventType["FAILURE_CASCADE_STARTED"] = "failure.cascade_started";
    SimForgeEventType["FAILURE_RESOLVED"] = "failure.resolved";
    SimForgeEventType["TARGET_RATE_LIMITED"] = "target.rate_limited";
    SimForgeEventType["TARGET_CONNECTION_RESET"] = "target.connection_reset";
    SimForgeEventType["TARGET_OVERLOADED"] = "target.overloaded";
    SimForgeEventType["WORKER_STARTED"] = "worker.started";
    SimForgeEventType["WORKER_CRASHED"] = "worker.crashed";
    SimForgeEventType["WORKER_RECOVERED"] = "worker.recovered";
})(SimForgeEventType || (exports.SimForgeEventType = SimForgeEventType = {}));
//# sourceMappingURL=simulation.events.js.map